---
- name: Some examples on linux server
  hosts: all
  become: true
  become_method: sudo
  gather_facts: true
  any_errors_fatal: true

  vars_files:
    - vars/main.yml

  roles:
    - role: ntp
    - role: timezone
    - role: add-repository
    - role: etc_hosts
    - role: packages
